apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonnaci-api
  template:
    metadata:
      labels:
        app: fibonnaci-api
    spec:
      containers:
        - name: fibonnaci-api
          image: evandrosouza89/fibonnaci-api:latest
          # Vertical scaling
          resources:
            requests:
              cpu: "200m"  # Request 200 milliCPU for this container
              memory: "256Mi"
            limits:
              cpu: "500m"  # Limit to 500 milliCPU for this container
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci-api-service
spec:
  selector:
    app: fibonnaci-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fibonacci-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fibonacci-api-deployment
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 3  # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  # Target average CPU utilization percentage